name: Deploy Flask with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask
      run: |
        nohup gunicorn --bind unix:/var/www/myapp/ipc.sock wsgi:app &

    - name: Set up Nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo rm /etc/nginx/sites-enabled/default
        echo 'server {
          listen 80;
          server_name _;
          
          location / {
            include proxy_params;
            proxy_pass http://unix:/var/www/myapp/ipc.sock;
          }
        }' | sudo tee /etc/nginx/sites-available/myapp
        sudo ln -s /etc/nginx/sites-available/myapp /etc/nginx/sites-enabled
        sudo systemctl restart nginx

    - name: Print IP and Port
      run: |
        echo "App is deployed on IP: $(curl -s ifconfig.me) and Port: 80"
