name: Deploy Flask App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 */5 * * *" # Runs every 5 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://github.com/${{ github.repository }}.git /tmp/repo
      - name: Change to the repo directory
        run: cd /tmp/repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r /tmp/repo/requirements.txt

      - name: Start Flask Server (Background)
        run: |
          nohup gunicorn --bind 0.0.0.0:5000 app:app &
          echo "Flask server started in the background. It will run for 5 hours."

      - name: Print public IP and port
        run: |
          public_ip=$(curl -s http://checkip.amazonaws.com)
          echo "Public IP is: $public_ip"
          echo "Port is: 5000"

      - name: Wait for 5 hours
        run: sleep 18000  # 5 hours in seconds

      - name: Kill Flask Server
        run: pkill gunicorn

      - name: Print Completion Message
        run: echo "Flask server has been shut down."
